version: '3.7'

services:
  php:
    image: php:5.6-apache
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    restart: always
    environment:
      PHP_ERROR_REPORTING: "E_ALL"
      PHP_DISPLAY_ERRORS: "On"
      PHP_UPLOAD_MAX_FILESIZE: "50M"
      PHP_POST_MAX_SIZE: "50M"
      PHP_MAX_EXECUTION_TIME: "30"
      PHP_MEMORY_LIMIT: "256M"

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example_password

volumes:
  db_data:
